### ISSUE TITLE
Is it possible to separate request from request-promise?

### ISSUE THREAD

**Issue by mochja** [antonku/jest-transform-stealthy-require#1]
Hello,

I have troubles in bigger codebase, where we use both request and rp, but in jest environment regular request module gets extended with request-promise and promise interface, changing all regular requests (made by `request`) to be promises and causing unhandled rejections.

Simplest testcase I could come up with:

``` js
const request = require('request');
const rp = require('request-promise-native');

test('request does not have promise interface', () => {
	expect(Object.is(request.Request.prototype.init, rp.Request.prototype.init)).toBe(false);
})
```

When I run in node (outside of jest environment), assertion passes, meaning the init method is not replaced for regular `request` module.

``` js
const request = require('request');
const rp = require('request-promise-native');
const assert = require('assert');

assert.ok(Object.is(request.Request.prototype.init, rp.Request.prototype.init) === false);
```

Is it possible to fully separate `request` from `request-promise` in jest environment?

**Comment by antonku** [comment]
Hi @mochja 

It seems that the issue happens when `request` is required before `request-promise-native`.
If the order of `require` statements is changed to the opposite the assertion passes.

This module (`jest-transform-stealthy-require`) relies on `jest.isolateModules()` to resolve conflicts between the imported modules. if you use `request` directly unfortunately the order of imports matters due to this issue: https://github.com/facebook/jest/issues/7863 

I would suggest changing the order of `require` statements in your codebase so that `request-promise-native` is imported before `request` if that is possible.

**Comment by mochja** [comment]
@antonku thanks this has worked!

I simply required the rp in the jest setup file.

**Comment by antonku** [comment]
Hi @mochja 

Thanks for the feedback, good to know that it helped.
